version: '3'
services:
  heimdall:
    image: linuxserver/heimdall:2.6.1
    container_name: heimdall
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Ho_Chi_Minh
    volumes:
      - ./heimdall/config:/config
    ports:
      - 80:80
      - 443:443
    restart: always